### ISSUE TITLE
Convert-iniToOMACSVTemplate.ps1 - ini-File will not be created

### ISSUE THREAD

**Issue by BenjaminK22** [Weatherlights/PolicyApplicator-for-Microsoft-Intune#3]
Hi Hauke,

when I try to create the [Greenshot-Fixed.zip](https://github.com/Weatherlights/PolicyApplicator-for-Microsoft-Intune/files/8351953/Greenshot-Fixed.zip) ini-File in "C:\Program Files\Greenshot" with your Convert-iniToOMACSV Template I get two 0x87d1fde8 Errors.
![image](https://user-images.githubusercontent.com/102375058/160155145-faa2d5f5-df73-4e59-925e-895e88e6bad2.png)

When I take a closer look in the Eventlog, I can see that these keys are missing:
CSP-URI (./Device/Vendor/MSFT/Policy/Config/Greenshot~Policy~Greenshot-Fixed_ini/Greenshot-Greenshot-Fixed_ini-0)
CSP-URI (./Device/Vendor/MSFT/Policy/Config/Greenshot~Policy~Greenshot-Fixed_ini/Greenshot-Greenshot-Fixed_ini-1)
![image](https://user-images.githubusercontent.com/102375058/160155777-d540d3f4-e21e-4790-b625-363ff32f3558.png)

I can confirm it with the Registry:
![image](https://user-images.githubusercontent.com/102375058/160156139-bf61bd0a-f2eb-4089-bd55-3560f70f18a6.png)

The second strange thing, this key is also missing:
![image](https://user-images.githubusercontent.com/102375058/160156464-73178a80-ab26-44ff-b768-82c48181d2c0.png)
![image](https://user-images.githubusercontent.com/102375058/160156655-29ece7eb-b769-47d1-844b-5f872ede9f63.png)

Can you please take a look, I really like to use this feature.

Best regards
Benjamin

**Comment by Weatherlights** [comment]
Hey :)

can you also provide me the converted csv file or the stuff in the ADMX ingestion value🙂?

Best
Hauke
________________________________
Von: Benjamin-Krauss ***@***.***>
Gesendet: Freitag, 25. März 2022 17:00
An: Weatherlights/PolicyApplicator-for-Microsoft-Intune ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Weatherlights/PolicyApplicator-for-Microsoft-Intune] Convert-iniToOMACSVTemplate.ps1 - ini-File will not be created (Issue #3)


Hi Hauke,

when I try to create the Greenshot-Fixed.zip<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWeatherlights%2FPolicyApplicator-for-Microsoft-Intune%2Ffiles%2F8351953%2FGreenshot-Fixed.zip&data=04%7C01%7Chauke%40hauke.us%7Cb185ae6531634727cfdb08da0e789098%7Ca61560d4444a49898c8619f38e4b4f7a%7C1%7C0%7C637838210034497079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qkuADYoHd%2FdyjLtTmgs4sTqPF2DuzFC7OxHA%2F3Nr4Cc%3D&reserved=0> ini-File in "C:\Program Files\Greenshot" with your Convert-iniToOMACSV Template I get two 0x87d1fde8 Errors.
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F102375058%2F160155145-faa2d5f5-df73-4e59-925e-895e88e6bad2.png&data=04%7C01%7Chauke%40hauke.us%7Cb185ae6531634727cfdb08da0e789098%7Ca61560d4444a49898c8619f38e4b4f7a%7C1%7C0%7C637838210034497079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V7lrAzUwWrwLQt838%2BU9c02F1vlArFIJRN4Cnmd5cGg%3D&reserved=0>

When I take a closer look in the Eventlog, I can see that he is missing those keys:
CSP-URI (./Device/Vendor/MSFT/Policy/Config/GreenshotPolicyGreenshot-Fixed_ini/Greenshot-Greenshot-Fixed_ini-0)
CSP-URI (./Device/Vendor/MSFT/Policy/Config/GreenshotPolicyGreenshot-Fixed_ini/Greenshot-Greenshot-Fixed_ini-1)
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F102375058%2F160155777-d540d3f4-e21e-4790-b625-363ff32f3558.png&data=04%7C01%7Chauke%40hauke.us%7Cb185ae6531634727cfdb08da0e789098%7Ca61560d4444a49898c8619f38e4b4f7a%7C1%7C0%7C637838210034497079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5EaWsWoa%2FPPc5HtCIgjJJkf5uSprWnPpiRWcN3if%2F%2Fo%3D&reserved=0>

I can confirm it with the Registry:
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F102375058%2F160156139-bf61bd0a-f2eb-4089-bd55-3560f70f18a6.png&data=04%7C01%7Chauke%40hauke.us%7Cb185ae6531634727cfdb08da0e789098%7Ca61560d4444a49898c8619f38e4b4f7a%7C1%7C0%7C637838210034497079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LVi%2BVVhEM6xQw7Nj0owG7BwbXBVp7VFpGwyZWQnoeI4%3D&reserved=0>

The second strange thing, this key is also missing:
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F102375058%2F160156464-73178a80-ab26-44ff-b768-82c48181d2c0.png&data=04%7C01%7Chauke%40hauke.us%7Cb185ae6531634727cfdb08da0e789098%7Ca61560d4444a49898c8619f38e4b4f7a%7C1%7C0%7C637838210034497079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0cFi6zTjzQzm%2B3VX7aDwWpTtYjvVXQHewzwbdRoi7RU%3D&reserved=0>
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F102375058%2F160156655-29ece7eb-b769-47d1-844b-5f872ede9f63.png&data=04%7C01%7Chauke%40hauke.us%7Cb185ae6531634727cfdb08da0e789098%7Ca61560d4444a49898c8619f38e4b4f7a%7C1%7C0%7C637838210034497079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1%2FHgGr9lUKPe9EsqdPKNatDNk8FrszXzfxVRoLj5mc0%3D&reserved=0>

Can you please take a look, I really like to use this feature.

Best regards
Benjamin

**Comment by BenjaminK22** [comment]
Yes no problem :)

Here you've got the csv-File:
[Greenshot-Fixed_csv.zip](https://github.com/Weatherlights/PolicyApplicator-for-Microsoft-Intune/files/8355031/Greenshot-Fixed_csv.zip)

And the PS commands:
& 'C:\Program Files (x86)\PolicyApplicator Conversion Kit\Convert-iniToOMACSVTemplate.ps1' -FilePath ".\Greenshot-Fixed.ini" -PathOnTargetSystem "C:\Program Files\Greenshot\Greenshot-Fixed.ini" -AppName "Greenshot" -AppPolicyName "Greenshot-Fixed.ini" -Context Machine -OutputFilePath ".\Greenshot-Fixed.csv"

& 'C:\Program Files (x86)\PolicyApplicator Conversion Kit\Invoke-CSVToIntuneUpload.ps1' -FilePath ".\Greenshot-Fixed.csv" -PolicyName "Greenshot - Default Config"

**Comment by Weatherlights** [comment]
Hey

I found the issue and released version 1.0.7.7 with the fix. You can download it from the release page and try it. The release within the Microsoft Store will also be updated but this takes a little longer :).

Best
Hauke

**Comment by BenjaminK22** [comment]
It's working now :) thanks my friend
![image](https://user-images.githubusercontent.com/102375058/160438942-89258553-2b1d-4de7-9f4d-d5efe6fe1762.png)

**Comment by Weatherlights** [comment]
Very welcome ;)

**Comment by Weatherlights** [comment]
Hey

Mixed up a variable. Will fix this during the next two Days :).

Best
Haube
